# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_auto_20180323_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(default='', max_length=254, null=True),
        ),
    ]
