# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_auto_20180323_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='value', max_length=7),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(default='value', max_length=254),
        ),
    ]
